name: Test

on:
  workflow_run:
    workflows: [deploy]
    types: [completed]
    branches: [deploy]

env:
  ACCOUNT_URI: ${{ secrets.ACCOUNT_URI }}
  ACCOUNT_KEY: ${{ secrets.ACCOUNT_KEY }}
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
  CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
  DEVICE_CONNECTION_STRING: ${{ secrets.DEVICE_CONNECTION_STRING }}


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_test.txt
    - name: Running Test
      run: |
        python test_auto.py
